matrix:
  include:
  - language: ruby
    name: YAML Linting (rvm 3.0)
    rvm: 3.0
    before_install:
    - git clone https://github.com/TravisToolbox/yaml-lint
    install:
    - "./yaml-lint/install.sh"
    script:
    - "./yaml-lint/scan.sh"
  - language: bash
    name: Shellcheck (Bash)
    os: linux
    arch: arm64-graviton2
    before_install:
    - git clone https://github.com/TravisToolbox/shellcheck
    install:
    - "./shellcheck/install.sh"
    script:
    - "./shellcheck/scan.sh"
  - language: ruby
    name: Link Checking (rvm 3.0)
    rvm: 3.0
    env:
    - WHITELIST="https://img.shields.io"
    - EXCLUDE_FILES="CHANGELOG.md"
    before_install:
    - git clone https://github.com/TravisToolbox/awesomebot
    install:
    - "./awesomebot/install.sh"
    script:
    - "./awesomebot/scan.sh"
notifications:
  email: false
  slack:
    secure: bNsaveWsQisY6saTt1WhrjY31vjmcz0mb4nTVB8oMAzUfM8fLU3bn2Fvm7Po68ZGcBabVSGQ/f+qLx710tMkqsMoJ1b1T5jAQLS18JhGWNdcW5FlBlZW9AX4uVea/CdoAH1s75netTj/FNwvNx3WVbNnQpxQ/rSo5mU2caL3qk+noZlX7T93CQk+GEkSK7bP77X148lYZZw6qQuMH8IeVIeOZ6O3VOz+HWuxsBjlRv8URUmT0mcLoclhRwmnrAlh7Nye/TOvyjTOwGWLsiobNMvI6YAHPYTPSwPksg0IFCHMjEBjw2w2rcgCu6IB1cdVfeBxSeDqI2NDlZ7RBxoOprX51oZqXMYN9wLF11SUtTm5TaSBBj794eyKXJ6AFi+LzOMdFDPBdOCyK13u6Z0B93/sqV9G8+NjU8Ac3S+SJckZS3bcUhPzCg7VU8jrU2lCr+f8XxFPx7Fio/eOB4U5L5L/J2p7nKejKUHrmbon2cQ6zXZJNsHS/GTcmmHX/ZAnPa69AkR/kwk/9jAkj7gvAQ7CbOd6pqJdFkocZvA2B3CLTCytzW7srzV1UQwyXizdLmoUSlgn02XxADV1naPS4TwOtYvWJ/TzMiNqPyc70C0vypkN8NsWuFx17TCtDZ+yCCopufY1St0BX1QX2XlU8w6sops6aanfG7CokGmGP8Y=
